name: Daily Collection - Webhook Trigger

on:
  # 每天早上 9:00 CST (UTC 1:00)
  schedule:
    - cron: '0 1 * * *'
  # 允許手動觸發
  workflow_dispatch:

jobs:
  trigger-collection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Collection via Webhook
        run: |
          echo "🚀 Triggering data collection at $(date)"
          
          # Get Railway service URL
          RAILWAY_URL="${{ secrets.RAILWAY_SERVICE_URL }}"
          
          # Default URL if not provided (user needs to set this)
          if [ -z "$RAILWAY_URL" ]; then
            echo "⚠️  RAILWAY_SERVICE_URL secret not set"
            echo "💡 Please set RAILWAY_SERVICE_URL to your Railway service URL"
            echo "   Example: https://your-service.railway.app"
            exit 1
          fi
          
          echo "📡 Sending request to: ${RAILWAY_URL}/trigger"
          
          # Call the webhook endpoint
          response=$(curl -s -X POST "${RAILWAY_URL}/trigger" \
            -H "Content-Type: application/json" \
            -w "HTTP_STATUS:%{http_code}" \
            -d '{"source": "github-actions"}' || echo "CURL_FAILED")
          
          # Parse response
          if echo "$response" | grep -q "CURL_FAILED"; then
            echo "❌ Failed to connect to Railway service"
            echo "🔍 Please check if Railway service is running"
            exit 1
          fi
          
          http_status=$(echo "$response" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          response_body=$(echo "$response" | sed 's/HTTP_STATUS:[0-9]*$//')
          
          echo "📊 HTTP Status: $http_status"
          echo "📋 Response: $response_body"
          
          if [ "$http_status" -eq 200 ]; then
            echo "✅ Collection triggered successfully!"
          else
            echo "❌ Failed to trigger collection (HTTP $http_status)"
            exit 1
          fi
      
      - name: Wait and Check Status
        run: |
          echo "⏰ Waiting 10 seconds for collection to start..."
          sleep 10
          
          # Check status endpoint
          RAILWAY_URL="${{ secrets.RAILWAY_SERVICE_URL }}"
          
          if [ -n "$RAILWAY_URL" ]; then
            echo "📊 Checking collection status..."
            
            status_response=$(curl -s "${RAILWAY_URL}/status" || echo "FAILED")
            
            if [ "$status_response" != "FAILED" ]; then
              echo "📋 System Status:"
              echo "$status_response"
            else
              echo "⚠️  Could not fetch status"
            fi
          fi
          
          echo "✅ Workflow completed"
          echo "💡 Check Railway logs for detailed collection results"